version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.server
        ports:
            - "22300:22300"
        volumes:
            - ./packages/server:/home/joplin/packages/server
            - /home/joplin/packages/server/node_modules/
    db:
        build:
            context: .
            dockerfile: Dockerfile.db
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=joplin
            - POSTGRES_USER=joplin
            - POSTGRES_DB=joplin