version: '3'

services:
    # app:
    #   build:
    #     context: .
    #     dockerfile: Dockerfile.server
    #   ports:
    #     - "22300:22300"
    #   image: app
    #   container_name: app
    db:
        build:
            context: .
            dockerfile: Dockerfile.db
        environment:
            # TODO: get password from env file
            - POSTGRES_PASSWORD=joplin